apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasterixGM/Argocd-test-apps-waves
    path: operator
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy: {}