apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/dependency: redis
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/dependency: redis
spec:
  project: default
  source:
    repoURL: https://github.com/MasterixGM/Argocd-test-apps-waves
    path: apps
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/dependency: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---        
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/dependency: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
