apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/dependency: redis
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/dependency: redis
spec:
  project: default
  source:
    repoURL: https://github.com/nginxinc/kubernetes-ingress
    path: deployments/helm-chart
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
