apiVersion: v1
kind: Namespace
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts/redis
    path: redis
    targetRevision: 20.9.0
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
